// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdwKSE6kLhxLXUleD9p1lmwOeG96FJiqs',
    appId: '1:738895209238:web:f48fd7981680a8aec46637',
    messagingSenderId: '738895209238',
    projectId: 'fir-task-8b48c',
    authDomain: 'fir-task-8b48c.firebaseapp.com',
    storageBucket: 'fir-task-8b48c.firebasestorage.app',
    measurementId: 'G-BQ1SPRF551',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjrOvEZjIEwztaMwIFsQVaa4g-CnVrWoU',
    appId: '1:738895209238:android:16cd56fe201d05f2c46637',
    messagingSenderId: '738895209238',
    projectId: 'fir-task-8b48c',
    storageBucket: 'fir-task-8b48c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvzfkUtRYS26aT_uoeYFnj0iQ2beSREC8',
    appId: '1:738895209238:ios:880e288185e83bbdc46637',
    messagingSenderId: '738895209238',
    projectId: 'fir-task-8b48c',
    storageBucket: 'fir-task-8b48c.firebasestorage.app',
    iosBundleId: 'com.example.module5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvzfkUtRYS26aT_uoeYFnj0iQ2beSREC8',
    appId: '1:738895209238:ios:880e288185e83bbdc46637',
    messagingSenderId: '738895209238',
    projectId: 'fir-task-8b48c',
    storageBucket: 'fir-task-8b48c.firebasestorage.app',
    iosBundleId: 'com.example.module5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdwKSE6kLhxLXUleD9p1lmwOeG96FJiqs',
    appId: '1:738895209238:web:e82762f6174823e4c46637',
    messagingSenderId: '738895209238',
    projectId: 'fir-task-8b48c',
    authDomain: 'fir-task-8b48c.firebaseapp.com',
    storageBucket: 'fir-task-8b48c.firebasestorage.app',
    measurementId: 'G-0PTH0SBWE9',
  );
}
